language: android
jdk:
    - oraclejdk7
    - oraclejdk8

env:
    - MALLOC_ARENA_MAX=2

android:
    components:
        - tools
        - build-tools-23.0.2
        - android-23
        - extra

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=/usr/lib/jvm/java-7-oracle
   


script:
    - bash gradlew :CollapsibleMenu:assemble
    - bash gradlew :DataBindingListView:assemble
    - bash gradlew :DataBindingRecycleView:assemble
    - bash gradlew :HelloRetroLambda:assemble
    - bash gradlew :RecycleViewExample:assemble
    - bash gradlew :BottomSheets:assemble
