language: android
jdk:
    - oraclejdk7
    - oraclejdk8
android:
    components:
        - build-tools-22.0.1
        - android-23
        - extra

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=/usr/lib/jvm/java-7-oracle
   


script: "bash gradlew build"
